/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gitflow.test;

public class App {
    public String getGreeting() {

        return "This is a small change in the app.";

    }

    public String secondString(){
        return "a second string. recompile maybe?";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println(new App().secondString());
    }
}
